---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-unsealer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openbao-unsealer
subjects:
- kind: ServiceAccount
  name: openbao-unsealer
  namespace: openbao-system