apiVersion: v1
kind: Secret
metadata:
  name: openbao-unseal-key
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  keys.json: {{ .Values.credentials | toJson | b64enc }}