apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: play
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "demo-role"
    vault.hashicorp.com/agent-inject-secret-config.txt: "kv/secret/myapp/config"
    vault.hashicorp.com/agent-inject-template-config.txt: |
      {{- with secret "kv/secret/myapp/config" -}}
      USERNAME={{ .Data.username }}
      PASSWORD={{ .Data.password }}
      {{- end }}
spec:
  serviceAccountName: demo-sa
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /vault/secrets/config.txt && sleep infinity"]
